version: "3"

services:
  zookeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"

  kafka:
    image: wurstmeister/kafka
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
#   start kafka and zookeeper
#   docker-compose -f docker-compose.yml up -d

#   stop and remove kafka and zookeeper
#   docker-compose down

#   dolist services
#   docker ps

#   go inside kafka and start shell
#   docker exec -it kafka /bin/sh

#   cd opt
#   cd kafka

#   create topic
#   @/opt/kafka_2.13-2.7.0 # =>
#   ./bin/kafka-topics.sh --create --zookeeper zookeeper:2181 --replication-factor 1 --partitions 1 --topic bikes

#   list topic
#   ./bin/kafka-topics.sh --list --zookeeper zookeeper:2181

#   create consumer
#   ./bin/kafka-console-consumer.sh --bootstrap-server localhost:9092 --topic bikes

#   tutorial :
#   https://www.youtube.com/watch?v=WnlX7w4lHvM
